apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-web-deployment
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      name: current
      app: web
  template:
    metadata:
      labels:
        name: current
        app: web
    spec:
      containers:
        - name: web
          image: 1pro/exam
          ports:
            - containerPort: 8080