apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-web-deployment
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      name: current
      app: web
  template:
    metadata:
      labels:
        name: current
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
      initContainers:
        - name: init
          image: busybox:stable
          command:
            - sh
            - -c
            - |
               echo $POD_NAME > /usr/share/nginx/html/index.html
               cat /var/lib/pod/* >> /usr/share/nginx/html/index.html
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
            - mountPath: /var/lib/pod
              name: info
      volumes:
        - name: volume
          emptyDir: {}
        - name: info
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels