apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: 1pro/exam
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "invalid"
      maxUnavailable: "invalid"