apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
  namespace: resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam
  template:
    metadata:
      labels:
        app: exam
    spec:
      containers:
        - name: exam
          image: 1pro/exam
          ports:
            - containerPort: 8080