apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: database
spec:
  limits:
    - default:
        memory: 32Mi
      defaultRequest:
        memory: 16Mi
      max:
        memory: 640Mi
      type: Container