apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: firewall
  labels:
    app: db
  spec:
    containers:
      - name: db
        image: 1pro/exam
        ports:
          - containerPort: 8080