apiVersion: v1
kind: Pod
metadata:
  name: agent
  namespace: firewall
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: busybox
          command: ["sh", "-c", "sleep 36000"]