apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-one
  namespace: app
spec:
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
        - name: one
          image: 1pro/exam
          ports:
            - containerPort: 8080