apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-two
  namespace: app
spec:
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
        - name: two
          image: 1pro/exam
          ports:
            - containerPort: 8080