apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-deploy
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotfix
  template:
    metadata:
      labels:
        app: hotfix
    spec:
      containers:
        - name: exam
          image: 1pro/exam
          ports:
            - containerPort: 8080